<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8" />
    <title>Challenge Urbano</title>
    <!-- <script src="../js/scripts.js"></script> -->
    <link rel="stylesheet" type="text/css" href="../css/styles.css"> <!-- Vincula tu archivo CSS -->
</head>
<body>
    <!-- Header -->
    <header>
        <nav>
            <ul>
                <li><a href="?controller=user&action=index">Home</a></li>
                <li><a href="?controller=user&action=createUser">Registro</a></li>
            </ul>
        </nav>
    </header>
