<?php 

include_once("views/header.phtml");

if ($_SESSION['registerData']['action'] == "create") {
    $titulo = "Crear Nuevo ";
    $boton = "Registrar";
} elseif ($_SESSION['registerData']['action'] == "update") {
    $titulo = "Actualizar ";
    $boton = "Actualizar";
}
?>
    <body>
        <h1><?=$titulo?> Usuario</h1>

        <!-- --- Mensaje del Registro --->
  
        <?php if(isset($_SESSION['register']) && $_SESSION['register'] != "Complete"): ?>
            <div id="mensaje-container">
                <strong class="mensaje_false">El Registro no se ha podido Completar Correctamente,<br> corrija los errores e intente nuevamente.</strong>
            </div>
        <?php endif; ?>

        <form action="?controller=user&action=save" method="POST">

            <input type="text" id="id" name="id" value="<?=$_SESSION['registerData']['id']?>">

            <label for="name">Nombre:</label><br>
            <input type="text" id="name" name="name" value="<?=$_SESSION['registerData']['name']?>" required>

            <?= isset($_SESSION["register"]['name']) ? $_SESSION["register"]['name'] : '' ?>
            <br><br>
            <label for="surname">Apellido:</label><br>
            <input type="text" id="surname" name="surname" value="<?=$_SESSION['registerData']['surname']?>" required>

            <?= isset($_SESSION["register"]['surname']) ? $_SESSION["register"]['surname'] : '' ?>
            <br><br>
            <label for="password1">Contraseña:</label><br>
            <input type="password" id="password1" name="password1" required><br>

            <br><br>
            <label for="password2">Repetir Contraseña:</label><br>
            <input type="password" id="password2" name="password2" required><br>

            <?= isset($_SESSION["register"]['password']) ? $_SESSION["register"]['password'] : '' ?>

            <br><br>
            <label for="email">Email:</label>
            <input type="email" id="email" name="email" value="<?=$_SESSION['registerData']['email']?>" required>

            <?= isset($_SESSION["register"]['email']) ? $_SESSION["register"]['email'] : '' ?>
            
            <input type="submit" value="<?=$boton?>">
            </br></br>
            <button onclick="limpiarFormulario()">Limpiar formulario</button>
        </form>
        <script>
        function limpiarFormulario() {
                window.location.href = '?controller=user&action=clearSession';
            }
        </script>
    </body>
<?php include_once("views/footer.phtml");?>
